{
 "title": "Kie Server Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kie Server State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"kieserver-metrics\"}"
    }
   ]
  },
  {
   "title": "Kie Server Start TIme",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    { "expr": "kie_server_start_time" }
   ]
  },
  {
   "title": "Active Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_container_running_total)"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_deployments_active_total)"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_job_running_total)"
    }
   ]
  },
  {
   "title": "Running Cases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_case_running_total)"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_process_instance_running_total)"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_task_added_total)"
    }
   ]
  },
  {
   "title": "SLA Violations",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_process_instance_sla_violated_total"
    }
   ]
  },
  {
   "title": "Execution Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kie_server_execution_error_total"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_task_failed_total)"
    }
   ]
  },
  {
   "title": "Exited Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_task_exited_total)"
    }
   ]
  },
  {
   "title": "Started Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_process_instance_started_total)"
    }
   ]
  },
  {
   "title": "Started Cases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_case_started_total)"
    }
   ]
  },
  {
   "title": "Registered Data Set Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_data_set_registered_total)"
    }
   ]
  },
  {
   "title": "Running Data Set Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_server_data_set_lookups_total)"
    }
   ]
  },
  {
   "title": "Data Set Queries Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(kie_server_data_set_execution_time_seconds_sum[1m])",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Data Set Query Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kie_server_data_set_execution_time_seconds_count"
    }
   ]
  },
  {
   "title": "Started Process Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kie_server_process_instance_started_total[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Process Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_process_instance_duration_seconds_sum[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Work Item Average Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_work_item_duration_seconds_sum[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Work Items Executions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "kie_server_work_item_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Case Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_case_duration_seconds_sum[1m])",
     "legendFormat": "{{case_definition_id}}"
    }
   ]
  },
  {
   "title": "Task Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_server_task_duration_seconds_sum[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}